/* The following code was generated by JFlex 1.4.3 on 18/09/22 07:57 PM */

package codigo;
import static codigo.Tokens.*;
import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 18/09/22 07:57 PM from the specification file
 * <tt>D:/Descargas/SEMESTRE 2022/COMPILADORES 1/LAB/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\13\2\0\1\3\22\0\1\50\1\0\1\33\1\0"+
    "\1\37\1\57\1\0\1\36\1\53\1\54\1\17\1\15\1\46\1\16"+
    "\1\32\1\20\1\2\11\41\1\0\1\45\1\0\1\14\1\44\1\62"+
    "\1\0\1\30\1\55\1\27\1\23\1\6\1\5\1\43\1\12\1\4"+
    "\1\52\1\1\1\7\1\21\1\26\1\22\1\24\1\51\1\35\1\10"+
    "\1\25\1\47\1\34\1\11\1\1\1\56\1\1\1\60\1\0\1\61"+
    "\1\0\1\31\1\0\1\30\1\55\1\27\1\23\1\6\1\5\1\43"+
    "\1\12\1\4\1\52\1\1\1\7\1\21\1\26\1\22\1\24\1\51"+
    "\1\35\1\10\1\25\1\47\1\34\1\11\1\1\1\56\1\1\1\40"+
    "\1\0\1\42\101\0\1\62\uff40\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\6\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\14\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\2\1\1\20\1\21\1\22\2\0\1\2"+
    "\1\23\12\0\1\24\4\0\1\25\1\26\1\27\1\0"+
    "\1\30\5\0\1\31\12\0\1\32\6\0\1\33\3\0"+
    "\1\34\20\0\1\35\11\0\1\36\3\0\1\37\22\0"+
    "\1\40\3\0\1\41\2\0\1\42\1\0\1\43\11\0"+
    "\1\44\7\0\1\45\5\0\1\46\1\0\1\47\1\50"+
    "\2\0\1\51\16\0\1\34\2\0\1\52\13\0\1\53"+
    "\23\0\1\54\16\0\1\55\1\0\1\56\1\57\4\0"+
    "\1\60\1\51\1\0\1\61\1\62\1\0\1\63\2\0"+
    "\1\64\3\0\1\65\2\0\1\66\3\0\1\67\2\0"+
    "\1\70\4\0\1\71\4\0\1\72\1\73\5\0\1\74"+
    "\7\0\1\75\1\0\1\76\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[305];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\u0198\0\u01cb\0\u01fe\0\63\0\63\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f"+
    "\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\u0561\0\u0297\0\63\0\63\0\63"+
    "\0\146\0\u0594\0\u05c7\0\146\0\u05fa\0\u062d\0\u0660\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\146\0\u07f8"+
    "\0\u082b\0\u085e\0\u0891\0\63\0\63\0\63\0\u08c4\0\u08f7"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\146\0\u0a29\0\u0a5c"+
    "\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0495"+
    "\0\63\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\63"+
    "\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b"+
    "\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023"+
    "\0\u1056\0\u1089\0\u10bc\0\u10ef\0\146\0\u1122\0\u1155\0\u1188"+
    "\0\u11bb\0\u11ee\0\u1221\0\u1254\0\u1287\0\u12ba\0\u0bc1\0\u12ed"+
    "\0\u1320\0\u1353\0\63\0\u1386\0\u13b9\0\u13ec\0\u141f\0\u1452"+
    "\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\u15b7\0\u15ea"+
    "\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9\0\63\0\u171c\0\u174f"+
    "\0\u1782\0\63\0\u17b5\0\u17e8\0\146\0\u181b\0\146\0\u184e"+
    "\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3\0\u19e6"+
    "\0\146\0\u1a19\0\u1a4c\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18\0\u1b4b"+
    "\0\146\0\u1b7e\0\u1bb1\0\u1be4\0\u1c17\0\u1c4a\0\146\0\u1c7d"+
    "\0\u1cb0\0\146\0\u1ce3\0\u1d16\0\u1d49\0\u1d7c\0\u1daf\0\u1de2"+
    "\0\u1e15\0\u1e48\0\u1e7b\0\u1eae\0\u1ee1\0\u1f14\0\u1f47\0\u1f7a"+
    "\0\u1fad\0\u1fe0\0\u2013\0\146\0\u2046\0\u2079\0\63\0\u20ac"+
    "\0\u20df\0\u2112\0\u2145\0\u2178\0\u21ab\0\u21de\0\u2211\0\u2244"+
    "\0\u2277\0\u22aa\0\146\0\u22dd\0\u2310\0\u2343\0\u2376\0\u23a9"+
    "\0\u23dc\0\u240f\0\u2442\0\u2475\0\u24a8\0\u24db\0\u250e\0\u2541"+
    "\0\u2574\0\u25a7\0\u25da\0\u260d\0\u2640\0\u2673\0\146\0\u26a6"+
    "\0\u26d9\0\u270c\0\u273f\0\u2772\0\u27a5\0\u27d8\0\u280b\0\u283e"+
    "\0\u2871\0\u28a4\0\u28d7\0\u290a\0\u293d\0\146\0\u2970\0\u29a3"+
    "\0\146\0\u29d6\0\u2a09\0\u2a3c\0\u2a6f\0\63\0\63\0\u2aa2"+
    "\0\146\0\146\0\u2ad5\0\146\0\u2b08\0\u2b3b\0\146\0\u2b6e"+
    "\0\u2ba1\0\u2bd4\0\146\0\u2c07\0\u2c3a\0\63\0\u2c6d\0\u2ca0"+
    "\0\u2cd3\0\63\0\u2d06\0\u2d39\0\63\0\u2d6c\0\u2d9f\0\u2dd2"+
    "\0\u2e05\0\63\0\u2e38\0\u2e6b\0\u2e9e\0\u2ed1\0\63\0\63"+
    "\0\u2f04\0\u2f37\0\u2f6a\0\u2f9d\0\u2fd0\0\63\0\u3003\0\u3036"+
    "\0\u3069\0\u309c\0\u30cf\0\u3102\0\u3135\0\63\0\u3168\0\63"+
    "\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[305];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\3"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\3\1\26\1\27"+
    "\1\30\1\31\1\2\1\32\1\33\1\34\1\35\1\2"+
    "\1\36\1\4\1\37\1\3\1\2\1\40\1\41\1\3"+
    "\1\5\2\3\1\42\1\43\1\44\1\3\1\45\1\46"+
    "\1\47\1\50\64\0\2\51\1\0\7\51\6\0\10\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\1\51\1\4"+
    "\1\0\7\51\6\0\10\51\1\0\1\53\1\0\2\51"+
    "\3\0\1\4\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\7\0\1\5\44\0\1\5\13\0"+
    "\2\51\1\0\1\51\1\54\5\51\6\0\1\55\4\51"+
    "\1\56\2\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\1\57\2\51\1\60\3\51\6\0\7\51"+
    "\1\61\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\62\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\3\51\1\63\1\64\2\51\6\0\5\51\1\65"+
    "\2\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\1\51\1\66\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\1\67\1\51\1\70\4\51\6\0\4\51"+
    "\1\71\3\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\6\51\1\72\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\7\51\1\73\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\20\0"+
    "\1\74\1\75\61\0\1\74\1\0\1\75\25\0\1\76"+
    "\32\0\1\74\62\0\1\74\2\0\1\77\1\100\43\0"+
    "\2\51\1\0\1\101\1\51\1\102\4\51\6\0\1\51"+
    "\1\103\5\51\1\104\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\1\105\2\0"+
    "\1\51\1\106\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\2\51\1\107\4\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\1\51"+
    "\1\110\5\51\1\111\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\1\51\1\112\6\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\113"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\1\51\1\114\5\51\1\115\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\5\51\1\116\2\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\117\1\0\7\117\6\0\11\117\2\0\2\117"+
    "\3\0\1\117\1\0\1\117\3\0\1\117\1\0\2\117"+
    "\2\0\2\117\4\0\33\120\1\121\27\120\1\0\2\51"+
    "\1\0\2\51\1\122\4\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\2\51\1\123"+
    "\4\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\1\124\2\0\7\124\6\0\10\124\3\0\2\124"+
    "\1\0\1\125\3\0\1\124\3\0\1\124\1\0\2\124"+
    "\2\0\2\124\5\0\2\51\1\0\7\51\6\0\1\51"+
    "\1\126\6\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\1\51\1\127"+
    "\60\0\1\130\10\0\1\53\36\0\1\53\22\0\2\51"+
    "\1\0\7\51\6\0\3\51\1\131\4\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\1\132\6\51"+
    "\6\0\10\51\3\0\2\51\3\0\1\51\1\0\1\133"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\5\51\1\134\2\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\1\51\1\135\6\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\3\51\1\136\3\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\5\51\1\137\2\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\4\51\1\140"+
    "\2\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\1\141\2\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\4\51\1\142\3\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\2\51\1\143\4\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\10\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\144\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\10\51\3\0"+
    "\1\51\1\145\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\1\146\6\51\6\0\10\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\4\51\1\147\2\51\6\0"+
    "\6\51\1\150\1\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\4\0\17\77\1\151\1\0\42\77\13\100\1\0\47\100"+
    "\1\0\2\51\1\0\2\51\1\152\4\51\6\0\10\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\4\51\1\153\1\154\2\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\2\51\1\155\5\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\1\51\1\154\14\0\1\156\53\0\2\51"+
    "\1\0\7\51\6\0\10\51\1\157\2\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\4\51"+
    "\1\160\3\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\3\0\1\51\1\161"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\4\51\1\106\3\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\1\162\7\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\1\163\4\51\1\164\2\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\2\51"+
    "\1\165\5\51\3\0\1\51\1\166\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\2\51\1\106\5\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\117\1\0"+
    "\7\117\6\0\10\117\1\167\2\0\2\117\3\0\1\117"+
    "\1\0\1\117\3\0\1\117\1\0\2\117\2\0\2\117"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\1\51"+
    "\1\170\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\3\51\1\171\1\172\3\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\42\0\1\173\64\0\1\174\23\0\2\51"+
    "\1\0\7\51\6\0\1\51\1\175\6\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\4\51\1\176\3\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\1\51"+
    "\1\177\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\6\51\1\200\1\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\10\51\3\0"+
    "\1\51\1\201\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\10\51\1\202\2\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\7\51\1\203"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\4\51\1\204\2\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\6\51"+
    "\1\205\1\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\2\51\1\54\4\51\6\0\10\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\10\0\1\206\16\0\1\207"+
    "\40\0\2\51\1\0\7\51\6\0\1\51\1\210\6\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\6\51\1\211\1\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\10\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\212"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\1\213\6\51\6\0\10\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\3\51\1\140\3\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\4\51\1\214\3\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\2\51\1\215"+
    "\4\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\4\0\17\77\1\151\1\216\42\77\1\0\2\51\1\0"+
    "\7\51\6\0\5\51\1\217\2\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\1\51"+
    "\1\220\6\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\1\51\1\221\6\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\10\0\1\222\65\0\1\223"+
    "\54\0\2\51\1\0\2\51\1\224\4\51\6\0\10\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\7\51\1\225\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\2\51\1\226\4\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\1\51\1\227\6\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\10\51\1\230\2\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\231\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\2\51\1\232\4\51\6\0\10\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\7\51\1\233\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\2\51\1\234\5\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\2\51\1\235\4\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\1\51"+
    "\1\236\6\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\45\0"+
    "\1\237\22\0\2\51\1\0\3\51\1\240\3\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\2\51\1\241\4\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\1\242\6\51"+
    "\6\0\10\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\1\243\6\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\2\51\1\244"+
    "\4\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\11\0\1\245\2\0\1\246\10\0\1\247\2\0\1\250"+
    "\37\0\2\51\1\0\7\51\6\0\4\51\1\241\3\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\1\51\1\251\6\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\1\252\6\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\47\0\1\253"+
    "\23\0\1\254\57\0\2\51\1\0\7\51\6\0\5\51"+
    "\1\255\2\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\256\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\5\51"+
    "\1\257\2\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\5\51\1\260\2\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\7\51\1\261\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\1\51"+
    "\1\262\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\4\51\1\263\3\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\2\51\1\264"+
    "\5\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\10\51\3\0\1\51\1\265\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\26\0\1\266\41\0\2\51\1\0\7\51"+
    "\6\0\5\51\1\267\2\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\10\51\3\0"+
    "\1\51\1\270\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\30\0\1\271\7\0"+
    "\1\272\32\0\1\273\57\0\2\51\1\0\7\51\6\0"+
    "\5\51\1\274\2\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\6\51\1\275\1\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\5\0\2\51\1\0"+
    "\7\51\6\0\7\51\1\276\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\5\0\2\51\1\0\7\51\6\0\4\51\1\277"+
    "\3\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\10\51\3\0\1\51\1\300\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\6\0\1\301\36\0\1\301\22\0\2\51"+
    "\1\0\2\51\1\302\4\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\1\303\7\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\1\51\1\304\6\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\4\51"+
    "\1\305\2\51\6\0\10\51\3\0\2\51\3\0\1\51"+
    "\1\0\1\51\3\0\1\51\1\0\2\51\1\52\1\0"+
    "\2\51\53\0\1\306\17\0\1\307\1\0\1\310\60\0"+
    "\1\311\1\0\1\312\104\0\1\313\33\0\2\51\1\0"+
    "\7\51\6\0\1\51\1\314\6\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\53\0\1\315\20\0\1\316\56\0\2\51"+
    "\1\0\7\51\6\0\6\51\1\317\1\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\4\51\1\320\3\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\241\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\10\51\1\321\2\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\3\0\1\51\1\322"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\1\51\1\323\6\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\1\324\2\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\35\0\1\325\32\0\2\51"+
    "\1\0\7\51\6\0\6\51\1\326\1\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\1\51\1\241\6\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\34\0\1\327\62\0\1\330\60\0\1\331\35\0\2\51"+
    "\1\0\7\51\6\0\7\51\1\241\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\4\51"+
    "\1\332\3\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\2\51\1\333\5\51\3\0"+
    "\2\51\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\1\334"+
    "\6\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\5\51\1\335\2\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\6\0\1\336\36\0"+
    "\1\336\1\124\21\0\2\51\1\0\7\51\6\0\7\51"+
    "\1\337\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\1\340\6\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\7\51"+
    "\1\341\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\32\0\1\342"+
    "\77\0\1\343\25\0\1\344\101\0\1\345\72\0\1\346"+
    "\26\0\2\51\1\0\7\51\6\0\5\51\1\347\2\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\34\0\1\350\40\0"+
    "\1\351\55\0\2\51\1\0\2\51\1\352\4\51\6\0"+
    "\10\51\3\0\2\51\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\5\0\2\51"+
    "\1\0\7\51\6\0\7\51\1\353\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\55\0\1\354\12\0\2\51\1\0\7\51"+
    "\6\0\7\51\1\355\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\26\0\1\356\67\0\1\357\34\0\2\51\1\0\1\360"+
    "\6\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\41\0\1\361\34\0\1\362\102\0\1\363\34\0\2\51"+
    "\1\0\2\51\1\364\4\51\6\0\10\51\3\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\2\51\1\365"+
    "\4\51\6\0\10\51\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\5\0\2\51\1\0\7\51\6\0\10\51\3\0\1\51"+
    "\1\366\3\0\1\51\1\0\1\51\3\0\1\51\1\0"+
    "\2\51\1\52\1\0\2\51\5\0\2\51\1\0\7\51"+
    "\6\0\7\51\1\367\3\0\2\51\3\0\1\51\1\0"+
    "\1\51\3\0\1\51\1\0\2\51\1\52\1\0\2\51"+
    "\46\0\1\124\21\0\2\51\1\0\7\51\6\0\5\51"+
    "\1\241\2\51\3\0\2\51\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\3\0\1\51\1\370"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\10\51\3\0\1\51\1\371\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\33\0"+
    "\1\372\102\0\1\373\41\0\1\374\56\0\1\375\70\0"+
    "\1\376\41\0\1\377\110\0\1\u0100\26\0\2\51\1\0"+
    "\4\51\1\u0101\2\51\6\0\10\51\3\0\2\51\3\0"+
    "\1\51\1\0\1\51\3\0\1\51\1\0\2\51\1\52"+
    "\1\0\2\51\5\0\2\51\1\0\7\51\6\0\10\51"+
    "\3\0\1\51\1\u0102\3\0\1\51\1\0\1\51\3\0"+
    "\1\51\1\0\2\51\1\52\1\0\2\51\53\0\1\u0103"+
    "\14\0\2\51\1\0\4\51\1\u0104\2\51\6\0\10\51"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\35\0\1\u0105\53\0"+
    "\1\u0106\41\0\2\51\1\0\7\51\6\0\7\51\1\u0107"+
    "\3\0\2\51\3\0\1\51\1\0\1\51\3\0\1\51"+
    "\1\0\2\51\1\52\1\0\2\51\34\0\1\u0108\54\0"+
    "\1\u0109\75\0\1\u010a\26\0\2\51\1\0\7\51\6\0"+
    "\10\51\3\0\1\51\1\241\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\3\0\1\51\1\204"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\5\0\2\51\1\0\7\51\6\0"+
    "\10\51\3\0\1\51\1\u010b\3\0\1\51\1\0\1\51"+
    "\3\0\1\51\1\0\2\51\1\52\1\0\2\51\5\0"+
    "\2\51\1\0\7\51\6\0\10\51\1\u010c\2\0\2\51"+
    "\3\0\1\51\1\0\1\51\3\0\1\51\1\0\2\51"+
    "\1\52\1\0\2\51\10\0\1\u010d\104\0\1\u010e\61\0"+
    "\1\u010f\60\0\1\u0110\45\0\1\u0111\62\0\1\u0112\60\0"+
    "\1\206\104\0\1\u0113\55\0\1\u0114\76\0\1\u0115\33\0"+
    "\1\u0116\102\0\1\u0117\56\0\1\u0118\75\0\1\u0119\47\0"+
    "\1\u011a\66\0\1\u011b\61\0\1\u011c\43\0\1\u011d\75\0"+
    "\1\u011e\50\0\1\u011f\101\0\1\u0120\64\0\1\u0121\57\0"+
    "\1\u0122\72\0\1\u0123\52\0\1\u0124\43\0\1\u0125\64\0"+
    "\1\u0126\60\0\1\377\104\0\1\u0127\67\0\1\u0128\53\0"+
    "\1\u0129\71\0\1\u012a\47\0\1\u012b\65\0\1\u012c\41\0"+
    "\1\u012d\66\0\1\u012e\102\0\1\u012f\54\0\1\u0130\47\0"+
    "\1\u0131\53\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12699];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\2\11\20\1\6\11\2\1\3\11"+
    "\2\0\2\1\12\0\1\1\4\0\3\11\1\0\1\1"+
    "\5\0\1\1\12\0\1\11\6\0\1\11\3\0\1\1"+
    "\20\0\1\1\11\0\1\1\3\0\1\11\22\0\1\11"+
    "\3\0\1\11\2\0\1\1\1\0\1\1\11\0\1\1"+
    "\7\0\1\1\5\0\1\1\1\0\2\1\2\0\1\1"+
    "\16\0\1\1\2\0\1\11\13\0\1\1\23\0\1\1"+
    "\16\0\1\1\1\0\2\1\4\0\2\11\1\0\2\1"+
    "\1\0\1\1\2\0\1\1\3\0\1\1\2\0\1\11"+
    "\3\0\1\11\2\0\1\11\4\0\1\11\4\0\2\11"+
    "\5\0\1\11\7\0\1\11\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[305];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 190) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 61: 
          { lexeme=yytext(); return Parametros;
          }
        case 64: break;
        case 34: 
          { lexeme=yytext(); return Para;
          }
        case 65: break;
        case 44: 
          { lexeme=yytext(); return Funcion;
          }
        case 66: break;
        case 58: 
          { lexeme=yytext(); return ImprimirSalto;
          }
        case 67: break;
        case 54: 
          { lexeme=yytext(); return FinSegun;
          }
        case 68: break;
        case 51: 
          { lexeme=yytext(); return Mientras;
          }
        case 69: break;
        case 33: 
          { lexeme=yytext(); return OSi;
          }
        case 70: break;
        case 16: 
          { lexeme = yytext(); return CorcheteA;
          }
        case 71: break;
        case 4: 
          { lexeme=yytext(); return Linea;
          }
        case 72: break;
        case 46: 
          { lexeme=yytext(); return Imprimir;
          }
        case 73: break;
        case 11: 
          { lexeme = yytext(); return LLaveC;
          }
        case 74: break;
        case 29: 
          { lexeme=yytext(); return Módulo;
          }
        case 75: break;
        case 32: 
          { lexeme=yytext(); return ComentarioMultilinea;
          }
        case 76: break;
        case 40: 
          { lexeme=yytext(); return Hacer;
          }
        case 77: break;
        case 57: 
          { lexeme=yytext(); return FinMetodo;
          }
        case 78: break;
        case 18: 
          { lexeme = yytext(); return Interrogacion1;
          }
        case 79: break;
        case 27: 
          { lexeme=yytext(); return LLamada;
          }
        case 80: break;
        case 60: 
          { lexeme=yytext(); return FinMientras;
          }
        case 81: break;
        case 14: 
          { lexeme = yytext(); return ParentesisA;
          }
        case 82: break;
        case 19: 
          { lexeme=yytext(); return Reservadas;
          }
        case 83: break;
        case 9: 
          { lexeme=yytext(); return Division;
          }
        case 84: break;
        case 35: 
          { lexeme=yytext(); return Como;
          }
        case 85: break;
        case 45: 
          { lexeme=yytext(); return Repetir;
          }
        case 86: break;
        case 23: 
          { lexeme=yytext(); return Asignacion;
          }
        case 87: break;
        case 63: 
          { lexeme=yytext(); return Incremental;
          }
        case 88: break;
        case 2: 
          { lexeme=yytext(); return Numero;
          }
        case 89: break;
        case 24: 
          { lexeme=yytext(); return Comentario;
          }
        case 90: break;
        case 56: 
          { lexeme=yytext(); return ConValor;
          }
        case 91: break;
        case 55: 
          { lexeme=yytext(); return HastaQue;
          }
        case 92: break;
        case 3: 
          { /*ignore*/
          }
        case 93: break;
        case 17: 
          { lexeme = yytext(); return CorcheteC;
          }
        case 94: break;
        case 62: 
          { lexeme=yytext(); return DeloContrario;
          }
        case 95: break;
        case 42: 
          { lexeme=yytext(); return FinSi;
          }
        case 96: break;
        case 25: 
          { lexeme=yytext(); return OperadorLogico;
          }
        case 97: break;
        case 26: 
          { lexeme=yytext(); return Cadena;
          }
        case 98: break;
        case 39: 
          { lexeme=yytext(); return Hasta;
          }
        case 99: break;
        case 12: 
          { lexeme=yytext(); return PuntoComa;
          }
        case 100: break;
        case 7: 
          { lexeme=yytext(); return Resta;
          }
        case 101: break;
        case 52: 
          { lexeme=yytext(); return Potencia;
          }
        case 102: break;
        case 49: 
          { lexeme=yytext(); return Entonces;
          }
        case 103: break;
        case 15: 
          { lexeme = yytext(); return ParentesisC;
          }
        case 104: break;
        case 30: 
          { lexeme=yytext(); return Variable;
          }
        case 105: break;
        case 47: 
          { lexeme=yytext(); return Ingresar;
          }
        case 106: break;
        case 53: 
          { lexeme=yytext(); return Retornar;
          }
        case 107: break;
        case 59: 
          { lexeme=yytext(); return FinFuncion;
          }
        case 108: break;
        case 1: 
          { lexeme=yytext(); return ERROR;
          }
        case 109: break;
        case 37: 
          { lexeme=yytext(); return Booleano;
          }
        case 110: break;
        case 20: 
          { lexeme=yytext(); return Si;
          }
        case 111: break;
        case 8: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 112: break;
        case 10: 
          { lexeme = yytext(); return LLaveA;
          }
        case 113: break;
        case 48: 
          { lexeme=yytext(); return FinPara;
          }
        case 114: break;
        case 31: 
          { lexeme=yytext(); return Caracter;
          }
        case 115: break;
        case 38: 
          { lexeme=yytext(); return Segun;
          }
        case 116: break;
        case 28: 
          { lexeme=yytext(); return Global;
          }
        case 117: break;
        case 5: 
          { lexeme=yytext(); return Igual;
          }
        case 118: break;
        case 36: 
          { lexeme=yytext(); return TipoDato;
          }
        case 119: break;
        case 13: 
          { lexeme=yytext(); return Coma;
          }
        case 120: break;
        case 41: 
          { lexeme = yytext(); return OperadorRelacional;
          }
        case 121: break;
        case 50: 
          { lexeme=yytext(); return Ejecutar;
          }
        case 122: break;
        case 43: 
          { lexeme=yytext(); return Metodo;
          }
        case 123: break;
        case 21: 
          { lexeme = yytext(); return OperadorAtribucion;
          }
        case 124: break;
        case 22: 
          { lexeme = yytext(); return OperadorIncremento;
          }
        case 125: break;
        case 6: 
          { lexeme=yytext(); return Suma;
          }
        case 126: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
