
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinSi = 22;
  public static final int PuntoComa = 18;
  public static final int Coma = 19;
  public static final int Metodo = 37;
  public static final int FinMientras = 33;
  public static final int OperadorIncremento = 56;
  public static final int Potencia = 5;
  public static final int Variable = 6;
  public static final int Repetir = 34;
  public static final int Ingresar = 14;
  public static final int OperadorRelacional = 53;
  public static final int OperadorAritmetico = 3;
  public static final int Asignacion = 17;
  public static final int Booleano = 10;
  public static final int Retornar = 36;
  public static final int FinMetodo = 38;
  public static final int Para = 28;
  public static final int ImprimirSalto = 45;
  public static final int OperadorRelacionalMMM = 50;
  public static final int OperadorAritmeticoM = 4;
  public static final int Ejecutar = 42;
  public static final int FinFuncion = 41;
  public static final int Cadena = 8;
  public static final int Segun = 25;
  public static final int Hacer = 26;
  public static final int EOF = 0;
  public static final int Global = 12;
  public static final int Booleano1 = 9;
  public static final int CorcheteC = 62;
  public static final int Not = 54;
  public static final int OperadorLogico = 47;
  public static final int error = 1;
  public static final int CorcheteA = 61;
  public static final int Funcion = 40;
  public static final int Imprimir = 44;
  public static final int OperadorRelacionalM = 48;
  public static final int Incremental = 31;
  public static final int ConValor = 16;
  public static final int FinPara = 30;
  public static final int OSi = 24;
  public static final int DeloContrario = 23;
  public static final int OperadorRelacionalMMMM = 51;
  public static final int HastaQue = 35;
  public static final int Entonces = 21;
  public static final int Parametros = 39;
  public static final int LLamada = 43;
  public static final int Global2 = 13;
  public static final int OperadorRelacionalMM = 49;
  public static final int Si = 20;
  public static final int Caracter = 11;
  public static final int OperadorAtribucion = 55;
  public static final int Mientras = 32;
  public static final int ParentesisC = 58;
  public static final int ParentesisA = 57;
  public static final int Como = 15;
  public static final int Interrogacion2 = 64;
  public static final int LLaveC = 60;
  public static final int Hasta = 29;
  public static final int Numero = 7;
  public static final int Interrogacion1 = 63;
  public static final int TipoDato = 46;
  public static final int LLaveA = 59;
  public static final int Igual = 2;
  public static final int OperadorRelacionalMMMMM = 52;
  public static final int FinSegun = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Igual",
  "OperadorAritmetico",
  "OperadorAritmeticoM",
  "Potencia",
  "Variable",
  "Numero",
  "Cadena",
  "Booleano1",
  "Booleano",
  "Caracter",
  "Global",
  "Global2",
  "Ingresar",
  "Como",
  "ConValor",
  "Asignacion",
  "PuntoComa",
  "Coma",
  "Si",
  "Entonces",
  "FinSi",
  "DeloContrario",
  "OSi",
  "Segun",
  "Hacer",
  "FinSegun",
  "Para",
  "Hasta",
  "FinPara",
  "Incremental",
  "Mientras",
  "FinMientras",
  "Repetir",
  "HastaQue",
  "Retornar",
  "Metodo",
  "FinMetodo",
  "Parametros",
  "Funcion",
  "FinFuncion",
  "Ejecutar",
  "LLamada",
  "Imprimir",
  "ImprimirSalto",
  "TipoDato",
  "OperadorLogico",
  "OperadorRelacionalM",
  "OperadorRelacionalMM",
  "OperadorRelacionalMMM",
  "OperadorRelacionalMMMM",
  "OperadorRelacionalMMMMM",
  "OperadorRelacional",
  "Not",
  "OperadorAtribucion",
  "OperadorIncremento",
  "ParentesisA",
  "ParentesisC",
  "LLaveA",
  "LLaveC",
  "CorcheteA",
  "CorcheteC",
  "Interrogacion1",
  "Interrogacion2"
  };
}

